services:
  postgres:
    image: debezium/postgres:16
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - pgnetwork
    command: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pgnetwork

  lenses:
    image: lensesio/box
    container_name: lenses
    environment:
      ADV_HOST: 127.0.0.1
      EULA: "https://licenses.lenses.io/download/lensesdl?id=933e42bc-9f60-11ef-9df4-42010af01003"
    ports:
      - "3030:3030"
      - "9092:9092"
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge

